#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Backend-neutral interfaces used by the sampling algorithms.

This module is intended as a first step towards separating:
- algorithm logic (MH / DAMH),
- runtime orchestration,
- communication backend (MPI / local / in-memory).

At the moment, the concrete implementations live elsewhere, e.g. in
``surrDAMH.modules.communication`` or in solver / surrogate classes.
The goal of these protocols is to document the *minimal contract* that
algorithms actually rely on.

TODO:
- Update ``modules/algorithms.py`` to depend on these interfaces instead
  of importing MPI-flavoured communication classes directly.
- Add local / in-process implementations for standalone sampling.
- Decide whether shutdown / finalization belongs here or should remain in
  higher-level runners such as ``process_SAMPLER.py``.
- Consider splitting solver access into synchronous vs asynchronous
  variants if future algorithms need non-blocking evaluations.
"""

from __future__ import annotations

from typing import Any, Protocol, runtime_checkable

import numpy.typing as npt

from surrDAMH.surrogates.parent import Evaluator


# Current code accepts both forms:
# 1) observations only
# 2) (observations, solver_tag)
#
# TODO:
# - Standardize this across the codebase.
# - A cleaner long-term option would be a small dataclass such as
#   ``ObservationResult(observations, solver_tag=0)``.
ObservationResult = npt.NDArray | tuple[npt.NDArray, int]


@runtime_checkable
class AlgorithmConfiguration(Protocol):
    """
    Minimal configuration surface needed by ``modules/algorithms.py``.

    This protocol intentionally includes only attributes that are actually used
    inside the algorithm module. It allows the algorithm code to avoid a direct
    runtime dependency on ``surrDAMH.configuration.Configuration``, which in the
    current codebase pulls in MPI.

    TODO:
    - Revisit this list once more orchestration logic is moved out of the
      algorithm module.
    - Consider splitting file-output related settings from algorithmic settings
      if a cleaner runtime architecture is introduced later.
    """

    output_dir: str
    transform_before_saving: bool
    save_snapshots_to_file: bool
    transform_before_surrogate: bool
    state_dependent_approximation: bool
    use_surrogate_gradients: bool


@runtime_checkable
class ObservationProvider(Protocol):
    """
    Minimal interface for anything that can evaluate model observations.

    This can be implemented by:
    - a local solver instance,
    - an MPI-backed solver pool client,
    - a surrogate exposed as a solver-like object.

    Algorithms currently use only two operations:
    1. provide parameters,
    2. fetch resulting observations.

    TODO:
    - Clarify whether implementations are allowed to evaluate eagerly in
      ``set_parameters()`` or only lazily in ``get_observations()``.
    - Consider renaming to ``ModelEvaluator`` in the future if that reads
      better than the transport-oriented name "provider".
    """

    def set_parameters(self, parameters: npt.ArrayLike) -> None:
        """Store or submit parameters for later evaluation."""
        ...

    def get_observations(self) -> ObservationResult:
        """
        Return observations for the most recently supplied parameters.

        Implementations may return:
        - ``observations``
        - ``(observations, solver_tag)``
        """
        ...

    def __call__(self, parameters: npt.ArrayLike) -> ObservationResult:
        """Convenience method for set_parameters + get_observations."""
        self.set_parameters(parameters)
        return self.get_observations()


@runtime_checkable
class SnapshotCollector(Protocol):
    """
    Minimal interface for recording / forwarding snapshots generated by a chain.

    In the current MPI setup this corresponds to sending snapshots to the
    collector. In a standalone setup this may become:
    - a no-op sink,
    - an in-memory sink,
    - a local trainer / updater hook.

    TODO:
    - Replace the loose ``list[Any]`` payload with a dedicated snapshot
      dataclass once the snapshot structure is stabilized.
    - Decide whether a sink should also expose batching / flush methods.
    """

    def send_to_collector(self, data: list[Any]) -> None:
        """Consume one snapshot payload produced by the sampler."""
        ...


@runtime_checkable
class EvaluatorProvider(Protocol):
    """
    Minimal interface for delivering surrogate evaluators to DAMH.

    The current MPI implementation supports asynchronous polling for a new
    evaluator. A local implementation can satisfy the same contract in a much
    simpler way, for example by storing the current evaluator in memory.

    TODO:
    - Revisit naming: "provider" is neutral, but "source" or
      ``EvaluatorManager`` may better reflect the intended responsibility.
    - Decide whether lifecycle methods such as
      ``get_evaluator_and_terminate()`` should be part of this interface or
      remain in orchestration code only.
    - If algorithms never truly need explicit ``request_evaluator()``, it may
      later be replaced by a pull-only API.
    """

    evaluator: Evaluator | None

    def request_evaluator(self) -> None:
        """Notify the backend that the algorithm is ready for an evaluator update."""
        ...

    def evaluator_is_available(self) -> bool:
        """Return ``True`` if an updated evaluator can be obtained immediately."""
        ...

    def get_evaluator(self) -> Evaluator:
        """Return the current or newly received evaluator."""
        ...


__all__ = [
    "AlgorithmConfiguration",
    "ObservationResult",
    "ObservationProvider",
    "SnapshotCollector",
    "EvaluatorProvider",
]
