#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Oct 22 19:46:42 2019

@author: simona
"""

class Auto:
    def __init__(self, crit):
        if crit==0:
            self.go = self.go0
        else:
            self.go = self.go1
    
    def go0(self):
        print('TU TU')
        
    def go1(self):
        print('TU TU TU TU')
        
    def test_go(self):
        self.go()